#!/usr/bin/python3

# did I make this program way more complicated than it needs to be? Yes, definitely.
# But do I now know how to write meson configs with Python in mind? Maybe?
# Worth the extra hours I spent on it, IMO.

from n2g import converter
import feedparser

if __name__ == "__main__":
    f = open("/home/bmueller/Downloads/notams.rss", "r")
    nfeed = feedparser.parse(f.read())

# TODO: read these in from a config file defined/deployed by meson. Add cli args
#    feeds = [
#        "https://ourairports.com/airports/ULMM/notams.rss"
#    ]

    notams = []
#    for feed in feeds:
#        nfeed = feedparser.parse(feed)
    for entry in nfeed.entries:
        notams.append("(" + entry.description[5:-6] + ")")
            # the text processing removes the <> tags and replaces with parens (to match expectations)
    
    n2g = converter.n2g(notams)
    print(n2g.to_geojson())
    #n2g.to_geojson()
