#!/usr/bin/python3

# did I make this program way more complicated than it needs to be? Yes, definitely.
# But do I now know how to write meson configs with Python in mind? Maybe?
# Worth the extra hours I spent on it, IMO.

# import PyNotam
from PyNotam import notam
import pkgutil

if __name__ == "__main__":
    print("hello2u")
    print("also hello")

    s = """(A1912/15 NOTAMN
Q) LOVV/QWPLW/IV/BO/W/000/130/4809N01610E001
A) LOVV B) 1509261100 C) 1509261230
E) PJE WILL TAKE PLACE AT AREA LAAB IN WALDE
PSN:N480930 E0161028 RADIUS - 1NM
F) GND G) FL130)"""
    n = notam.Notam.from_str(s)
    
